Time: 2025-08-29T14:26:40.736561
Error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Traceback:
Traceback (most recent call last):
  File "C:\venvs\excel_to_calendar_app\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\venvs\excel_to_calendar_app\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\venvs\excel_to_calendar_app\Lib\site-packages\flask\app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\venvs\excel_to_calendar_app\Lib\site-packages\flask\app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "C:\venvs\excel_to_calendar_app\Lib\site-packages\flask\helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\venvs\excel_to_calendar_app\Lib\site-packages\werkzeug\utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
